// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: pbft.proto

package pbft

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Pbft_Broadcast_FullMethodName  = "/pbft/Broadcast"
	Pbft_SendToNode_FullMethodName = "/pbft/SendToNode"
	Pbft_PrePrepare_FullMethodName = "/pbft/PrePrepare"
	Pbft_Prepare_FullMethodName    = "/pbft/Prepare"
)

// PbftClient is the client API for Pbft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PbftClient interface {
	Broadcast(ctx context.Context, in *ConMessage, opts ...grpc.CallOption) (*Response, error)
	SendToNode(ctx context.Context, in *ConMessage, opts ...grpc.CallOption) (*Response, error)
	PrePrepare(ctx context.Context, in *PrePrepareRequest, opts ...grpc.CallOption) (*PrePrepareResponse, error)
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*Prepared, error)
}

type pbftClient struct {
	cc grpc.ClientConnInterface
}

func NewPbftClient(cc grpc.ClientConnInterface) PbftClient {
	return &pbftClient{cc}
}

func (c *pbftClient) Broadcast(ctx context.Context, in *ConMessage, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Pbft_Broadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) SendToNode(ctx context.Context, in *ConMessage, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Pbft_SendToNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) PrePrepare(ctx context.Context, in *PrePrepareRequest, opts ...grpc.CallOption) (*PrePrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrePrepareResponse)
	err := c.cc.Invoke(ctx, Pbft_PrePrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*Prepared, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Prepared)
	err := c.cc.Invoke(ctx, Pbft_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PbftServer is the server API for Pbft service.
// All implementations must embed UnimplementedPbftServer
// for forward compatibility.
type PbftServer interface {
	Broadcast(context.Context, *ConMessage) (*Response, error)
	SendToNode(context.Context, *ConMessage) (*Response, error)
	PrePrepare(context.Context, *PrePrepareRequest) (*PrePrepareResponse, error)
	Prepare(context.Context, *PrepareRequest) (*Prepared, error)
	mustEmbedUnimplementedPbftServer()
}

// UnimplementedPbftServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPbftServer struct{}

func (UnimplementedPbftServer) Broadcast(context.Context, *ConMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedPbftServer) SendToNode(context.Context, *ConMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToNode not implemented")
}
func (UnimplementedPbftServer) PrePrepare(context.Context, *PrePrepareRequest) (*PrePrepareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrePrepare not implemented")
}
func (UnimplementedPbftServer) Prepare(context.Context, *PrepareRequest) (*Prepared, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedPbftServer) mustEmbedUnimplementedPbftServer() {}
func (UnimplementedPbftServer) testEmbeddedByValue()              {}

// UnsafePbftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PbftServer will
// result in compilation errors.
type UnsafePbftServer interface {
	mustEmbedUnimplementedPbftServer()
}

func RegisterPbftServer(s grpc.ServiceRegistrar, srv PbftServer) {
	// If the following call pancis, it indicates UnimplementedPbftServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pbft_ServiceDesc, srv)
}

func _Pbft_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_Broadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).Broadcast(ctx, req.(*ConMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_SendToNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).SendToNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_SendToNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).SendToNode(ctx, req.(*ConMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_PrePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrePrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).PrePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_PrePrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).PrePrepare(ctx, req.(*PrePrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pbft_ServiceDesc is the grpc.ServiceDesc for Pbft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pbft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbft",
	HandlerType: (*PbftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Broadcast",
			Handler:    _Pbft_Broadcast_Handler,
		},
		{
			MethodName: "SendToNode",
			Handler:    _Pbft_SendToNode_Handler,
		},
		{
			MethodName: "PrePrepare",
			Handler:    _Pbft_PrePrepare_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _Pbft_Prepare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbft.proto",
}
