// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: pbft.proto

package pbft

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Pbft_Broadcast_FullMethodName          = "/pbft/Broadcast"
	Pbft_PrePrepare_FullMethodName         = "/pbft/PrePrepare"
	Pbft_Prepare_FullMethodName            = "/pbft/Prepare"
	Pbft_ProcessTransaction_FullMethodName = "/pbft/ProcessTransaction"
	Pbft_Printdb_FullMethodName            = "/pbft/Printdb"
	Pbft_SendReply_FullMethodName          = "/pbft/SendReply"
	Pbft_GetBalanceRequest_FullMethodName  = "/pbft/GetBalanceRequest"
	Pbft_TransactionStream_FullMethodName  = "/pbft/TransactionStream"
	Pbft_ReceiverNewView_FullMethodName    = "/pbft/ReceiverNewView"
	Pbft_GetStatus_FullMethodName          = "/pbft/GetStatus"
)

// PbftClient is the client API for Pbft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PbftClient interface {
	Broadcast(ctx context.Context, in *Broadcast, opts ...grpc.CallOption) (*Response, error)
	PrePrepare(ctx context.Context, in *PrePrepareRequest, opts ...grpc.CallOption) (*PrePrepareResponse, error)
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*Prepared, error)
	ProcessTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*Reply, error)
	Printdb(ctx context.Context, in *Balrequest, opts ...grpc.CallOption) (*Balresponse, error)
	// rpc SendReply (statusrequest) returns ( Reply);
	SendReply(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*Reply, error)
	GetBalanceRequest(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	TransactionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransactionRequest, Reply], error)
	ReceiverNewView(ctx context.Context, in *Newview, opts ...grpc.CallOption) (*Empty, error)
	GetStatus(ctx context.Context, in *Statusrequest, opts ...grpc.CallOption) (*StatusReponse, error)
}

type pbftClient struct {
	cc grpc.ClientConnInterface
}

func NewPbftClient(cc grpc.ClientConnInterface) PbftClient {
	return &pbftClient{cc}
}

func (c *pbftClient) Broadcast(ctx context.Context, in *Broadcast, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Pbft_Broadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) PrePrepare(ctx context.Context, in *PrePrepareRequest, opts ...grpc.CallOption) (*PrePrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrePrepareResponse)
	err := c.cc.Invoke(ctx, Pbft_PrePrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*Prepared, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Prepared)
	err := c.cc.Invoke(ctx, Pbft_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) ProcessTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, Pbft_ProcessTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) Printdb(ctx context.Context, in *Balrequest, opts ...grpc.CallOption) (*Balresponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Balresponse)
	err := c.cc.Invoke(ctx, Pbft_Printdb_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) SendReply(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, Pbft_SendReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) GetBalanceRequest(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, Pbft_GetBalanceRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) TransactionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransactionRequest, Reply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Pbft_ServiceDesc.Streams[0], Pbft_TransactionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransactionRequest, Reply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Pbft_TransactionStreamClient = grpc.BidiStreamingClient[TransactionRequest, Reply]

func (c *pbftClient) ReceiverNewView(ctx context.Context, in *Newview, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Pbft_ReceiverNewView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pbftClient) GetStatus(ctx context.Context, in *Statusrequest, opts ...grpc.CallOption) (*StatusReponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReponse)
	err := c.cc.Invoke(ctx, Pbft_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PbftServer is the server API for Pbft service.
// All implementations must embed UnimplementedPbftServer
// for forward compatibility.
type PbftServer interface {
	Broadcast(context.Context, *Broadcast) (*Response, error)
	PrePrepare(context.Context, *PrePrepareRequest) (*PrePrepareResponse, error)
	Prepare(context.Context, *PrepareRequest) (*Prepared, error)
	ProcessTransaction(context.Context, *TransactionRequest) (*Reply, error)
	Printdb(context.Context, *Balrequest) (*Balresponse, error)
	// rpc SendReply (statusrequest) returns ( Reply);
	SendReply(context.Context, *Reply) (*Reply, error)
	GetBalanceRequest(context.Context, *BalanceRequest) (*BalanceResponse, error)
	TransactionStream(grpc.BidiStreamingServer[TransactionRequest, Reply]) error
	ReceiverNewView(context.Context, *Newview) (*Empty, error)
	GetStatus(context.Context, *Statusrequest) (*StatusReponse, error)
	mustEmbedUnimplementedPbftServer()
}

// UnimplementedPbftServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPbftServer struct{}

func (UnimplementedPbftServer) Broadcast(context.Context, *Broadcast) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedPbftServer) PrePrepare(context.Context, *PrePrepareRequest) (*PrePrepareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrePrepare not implemented")
}
func (UnimplementedPbftServer) Prepare(context.Context, *PrepareRequest) (*Prepared, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedPbftServer) ProcessTransaction(context.Context, *TransactionRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessTransaction not implemented")
}
func (UnimplementedPbftServer) Printdb(context.Context, *Balrequest) (*Balresponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Printdb not implemented")
}
func (UnimplementedPbftServer) SendReply(context.Context, *Reply) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReply not implemented")
}
func (UnimplementedPbftServer) GetBalanceRequest(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalanceRequest not implemented")
}
func (UnimplementedPbftServer) TransactionStream(grpc.BidiStreamingServer[TransactionRequest, Reply]) error {
	return status.Errorf(codes.Unimplemented, "method TransactionStream not implemented")
}
func (UnimplementedPbftServer) ReceiverNewView(context.Context, *Newview) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiverNewView not implemented")
}
func (UnimplementedPbftServer) GetStatus(context.Context, *Statusrequest) (*StatusReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPbftServer) mustEmbedUnimplementedPbftServer() {}
func (UnimplementedPbftServer) testEmbeddedByValue()              {}

// UnsafePbftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PbftServer will
// result in compilation errors.
type UnsafePbftServer interface {
	mustEmbedUnimplementedPbftServer()
}

func RegisterPbftServer(s grpc.ServiceRegistrar, srv PbftServer) {
	// If the following call pancis, it indicates UnimplementedPbftServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pbft_ServiceDesc, srv)
}

func _Pbft_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Broadcast)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_Broadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).Broadcast(ctx, req.(*Broadcast))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_PrePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrePrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).PrePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_PrePrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).PrePrepare(ctx, req.(*PrePrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_ProcessTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).ProcessTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_ProcessTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).ProcessTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_Printdb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Balrequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).Printdb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_Printdb_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).Printdb(ctx, req.(*Balrequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_SendReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).SendReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_SendReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).SendReply(ctx, req.(*Reply))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_GetBalanceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).GetBalanceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_GetBalanceRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).GetBalanceRequest(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_TransactionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PbftServer).TransactionStream(&grpc.GenericServerStream[TransactionRequest, Reply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Pbft_TransactionStreamServer = grpc.BidiStreamingServer[TransactionRequest, Reply]

func _Pbft_ReceiverNewView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Newview)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).ReceiverNewView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_ReceiverNewView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).ReceiverNewView(ctx, req.(*Newview))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pbft_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Statusrequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pbft_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).GetStatus(ctx, req.(*Statusrequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pbft_ServiceDesc is the grpc.ServiceDesc for Pbft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pbft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbft",
	HandlerType: (*PbftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Broadcast",
			Handler:    _Pbft_Broadcast_Handler,
		},
		{
			MethodName: "PrePrepare",
			Handler:    _Pbft_PrePrepare_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _Pbft_Prepare_Handler,
		},
		{
			MethodName: "ProcessTransaction",
			Handler:    _Pbft_ProcessTransaction_Handler,
		},
		{
			MethodName: "Printdb",
			Handler:    _Pbft_Printdb_Handler,
		},
		{
			MethodName: "SendReply",
			Handler:    _Pbft_SendReply_Handler,
		},
		{
			MethodName: "GetBalanceRequest",
			Handler:    _Pbft_GetBalanceRequest_Handler,
		},
		{
			MethodName: "ReceiverNewView",
			Handler:    _Pbft_ReceiverNewView_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Pbft_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransactionStream",
			Handler:       _Pbft_TransactionStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pbft.proto",
}
